# See https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml for all config options

default: true
line-length: false
fenced-code-language: false
first-line-h1: false
single-title: false
no-duplicate-heading: false
no-emphasis-as-heading: false
code-block-style: false
no-alt-text: false
no-inline-html: false
ul-indent:
  start_indent: 2
  start_indented: true
