continue_on_error: true
formatter:
  type: basic
  drop_merge_tag: true
  indentless_arrays: true
  max_line_length: 120
  retain_line_breaks_single: true
  scan_folded_as_literal: true
  trim_trailing_whitespace: true
