name: Coverage Map Action
description: |
  A GitHub Action that analyzes code coverage for files changed in a pull request,
  generates a visual treemap of test gaps, and enforces a coverage threshold.
author: maxbirkner
branding:
  icon: bar-chart-2
  color: green

inputs:
  lcov-file:
    description: The path to the lcov.info coverage report file
    required: true
    default: ./coverage/lcov.info
  coverage-threshold:
    description: The minimum acceptable coverage percentage
    required: true
    default: "80"
  target-branch:
    description: The target branch to compare changes against
    required: false
    default: main
  github-token:
    description: GitHub token to post PR comments
    required: true
  label:
    description: Optional label for comment identification (enables multiple instances)
    required: false
  source-code-pattern:
    description: |
      Optional glob pattern(s) for source code files to include in coverage analysis.
      Multiple patterns can be separated by commas (e.g., "src/**/*.ts,lib/**/*.js").
      If not provided, defaults to common source code extensions.
    required: false
  test-code-pattern:
    description: |
      Optional glob pattern(s) for test files to exclude from coverage analysis.
      Multiple patterns can be separated by commas (e.g., "**/*.test.ts,**/*.spec.js").
      If not provided, defaults to common test file patterns.
    required: false

outputs:
  coverage-percentage:
    description: The overall coverage percentage for changed files
  meets-threshold:
    description: Whether the coverage meets the specified threshold (true/false)
  files-analyzed:
    description: The number of changed files that were analyzed
  files-with-coverage:
    description: The number of changed files that have coverage data

runs:
  using: node24
  main: dist/index.js
