name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 24
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Setup pre-commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    name: Test Coverage Treemap Action

    steps:
    - name: Determine fetch depth
      id: base-depth
      run: echo "base-depth=$(expr ${{ github.event.pull_request.commits }} + 1)" | tee -a $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: ${{ steps.base-depth.outputs.base-depth }}

    - name: Dump Github context
      run: |
        set -x
        echo '${{ toJSON(github) }}'
        git log --oneline
        echo "base-depth=${{ steps.base-depth.outputs.base-depth }}"
        git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 24
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Build action
      run: |
        mkdir -p dist
        npm run package

    - name: Run Coveragemap action
      uses: ./
      with:
        lcov-file: "./coverage/lcov.info"
        coverage-threshold: "80"

    - name: Upload coverage reports
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: coverage-report
        path: coverage/
        retention-days: 3
